/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_java2;

import java.awt.Color;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author Freddie
 */
public class ViewDeck extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeck
     */
    int i = 200;
    public ViewDeck() {
        initComponents();
        timer();
    }
    
    public void timer(){
    final ScheduledExecutorService executorService = Executors.newSingleThreadScheduledExecutor();
    executorService.scheduleAtFixedRate(new Runnable() {
        @Override
        public void run() {
            jTextArea1.setBackground(new Color (0,0,0,i));
            jTextArea1.repaint();
            if (i != 0){
            i -= 20;}
            if (i == 0){
            jTextArea1.hide();
            }
        }
    }
            , 0, (long) 40, TimeUnit.MILLISECONDS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(0, 0, 1000, 800);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/R1.png"))); // NOI18N
        jLabel11.setText("  ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 240, 80, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/R3.png"))); // NOI18N
        jLabel12.setText("jLabel6");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 240, 80, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/R2.png"))); // NOI18N
        jLabel13.setText("jLabel5");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(120, 240, 80, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/M1.png"))); // NOI18N
        jLabel8.setText("  ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 60, 80, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/M3.png"))); // NOI18N
        jLabel9.setText("jLabel6");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 60, 80, 120);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/M2.png"))); // NOI18N
        jLabel10.setText("jLabel5");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 60, 80, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/K1.png"))); // NOI18N
        jLabel7.setText("  ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 60, 80, 120);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/K3.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 60, 80, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/VD_Cards/k2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 60, 80, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/BackGrounds/VD_Menu.png"))); // NOI18N
        jLabel4.setText("  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(640, 60, 340, 720);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/Buttons/Exit.png"))); // NOI18N
        jLabel3.setText("  ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(960, 10, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/Buttons/Minimize.png"))); // NOI18N
        jLabel2.setText("  ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(920, 10, 30, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_java2/Images/BackGrounds/View_DeckBG.png"))); // NOI18N
        jLabel1.setText("  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 800);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1000, 800);

        setSize(new java.awt.Dimension(1000, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState( Main_Menu.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDeck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
